# For Apple M1/2/3 chip, run:
# DOCKER_DEFAULT_PLATFORM=linux/arm64/v8 docker-compose up -d --build
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: My@Test@Password1
      ACCEPT_EULA: 1
